// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer/proto/customer.proto

package customerproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Id struct {
	Id                   *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_ffd930cef5f460de, []int{0}
}
func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (dst *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(dst, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type CustomerProto struct {
	Id                   *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Name                 *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Address              *string  `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Email                *string  `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerProto) Reset()         { *m = CustomerProto{} }
func (m *CustomerProto) String() string { return proto.CompactTextString(m) }
func (*CustomerProto) ProtoMessage()    {}
func (*CustomerProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_ffd930cef5f460de, []int{1}
}
func (m *CustomerProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerProto.Unmarshal(m, b)
}
func (m *CustomerProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerProto.Marshal(b, m, deterministic)
}
func (dst *CustomerProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerProto.Merge(dst, src)
}
func (m *CustomerProto) XXX_Size() int {
	return xxx_messageInfo_CustomerProto.Size(m)
}
func (m *CustomerProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerProto.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerProto proto.InternalMessageInfo

func (m *CustomerProto) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *CustomerProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CustomerProto) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *CustomerProto) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*Id)(nil), "customerproto.Id")
	proto.RegisterType((*CustomerProto)(nil), "customerproto.CustomerProto")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerClient is the client API for Customer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerClient interface {
	GetCustomer(ctx context.Context, in *Id, opts ...grpc.CallOption) (*CustomerProto, error)
}

type customerClient struct {
	cc *grpc.ClientConn
}

func NewCustomerClient(cc *grpc.ClientConn) CustomerClient {
	return &customerClient{cc}
}

func (c *customerClient) GetCustomer(ctx context.Context, in *Id, opts ...grpc.CallOption) (*CustomerProto, error) {
	out := new(CustomerProto)
	err := c.cc.Invoke(ctx, "/customerproto.Customer/GetCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServer is the server API for Customer service.
type CustomerServer interface {
	GetCustomer(context.Context, *Id) (*CustomerProto, error)
}

func RegisterCustomerServer(s *grpc.Server, srv CustomerServer) {
	s.RegisterService(&_Customer_serviceDesc, srv)
}

func _Customer_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customerproto.Customer/GetCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).GetCustomer(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _Customer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customerproto.Customer",
	HandlerType: (*CustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomer",
			Handler:    _Customer_GetCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer/proto/customer.proto",
}

func init() {
	proto.RegisterFile("customer/proto/customer.proto", fileDescriptor_customer_ffd930cef5f460de)
}

var fileDescriptor_customer_ffd930cef5f460de = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4d, 0x2e, 0x2d, 0x2e,
	0xc9, 0xcf, 0x4d, 0x2d, 0xd2, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x87, 0x71, 0xf5, 0xc0, 0x5c,
	0x21, 0x5e, 0x18, 0x1f, 0xcc, 0x55, 0x12, 0xe0, 0x62, 0xf2, 0x4c, 0x11, 0xe2, 0xe2, 0x62, 0xca,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd2, 0xe0, 0x54, 0xf2, 0xe4, 0xe2, 0x75, 0x86, 0x2a, 0x09, 0x00,
	0xeb, 0x40, 0x92, 0x14, 0xe2, 0xe1, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x02, 0xf3, 0xf8,
	0xb9, 0xd8, 0x13, 0x53, 0x52, 0x8a, 0x52, 0x8b, 0x8b, 0x25, 0x98, 0x15, 0x18, 0x35, 0x38, 0x85,
	0x78, 0xb9, 0x58, 0x53, 0x73, 0x13, 0x33, 0x73, 0x24, 0x58, 0x40, 0x5c, 0x23, 0x2f, 0x2e, 0x0e,
	0x98, 0x51, 0x42, 0x76, 0x5c, 0xdc, 0xee, 0xa9, 0x25, 0x70, 0xae, 0xa0, 0x1e, 0x8a, 0x3b, 0xf4,
	0x3c, 0x53, 0xa4, 0x64, 0xd0, 0x84, 0x50, 0x5c, 0x01, 0x08, 0x00, 0x00, 0xff, 0xff, 0x10, 0xf4,
	0xdd, 0xb7, 0xd7, 0x00, 0x00, 0x00,
}
